<?php return array (
  'style.css' => 'css样式文件',
  'head.php' => '公共头部文件',
  'foot.php' => '公共底部文件',
  'article_show.php' => '文章详情页',
  'down_list.php' => '下载列表页',
  'down_show.php' => '下载详情页',
  'index.php' => '首页',
  'message_show.php' => '留言页面',
  'news_list.php' => '新闻列表页',
  'news_show.php' => '新闻详情页',
  'product_list.php' => '产品列表页',
  'product_show.php' => '产品详情页',
  'search.php' => '搜索页面',
  'sys_message.php' => '系统消息提示',
  'sys_seo.php' => '系统头部seo',
  'sdfds.css' => 'css',
);?>